### ISSUE TITLE
Downloading files fails, how to debug?

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#54] opened 2019-09-02 11:27 UTC

**Comment by cmeng-git** [comment] 2019-09-03 01:36
In omemo media file sharing, all file transfers are using httpuload protocol. aTalk uses HttpUploadManager from smack library to send file to server, and it uses android DownloadManager to retrieve file from server.

From prelim testing, pending on android OS, aTalk failed in file transfer seems to due to  SSL handshake connection setup. You need a protocol analyser e.g. wireshark to find out the cause of the problem.

https://www.wireshark.org/

**Comment by cmeng-git** [comment] 2019-09-06 02:44
Below are the test observations on HttpFileTransfer on two test servers. The tests are carried out based on the following setup, the same test environment in all tests :
1. Between two android devices i.e. Note-3 (API-21) and Note-8 (API-29)
2. Two servers i.e. aTalkServer and testServer

Test Observations:
-------------------------
1. aTalkServer:
a. All upload and download of files work without problem.

2. testServer:
a. Sending file from Note-8 to Note-3; both send and receive work without problem.
b. Sending file from Note-3 to Note-8:
i. File send OK on Note-3.
ii. Note-8, start receiving file on "Accept" click, but the http download always failed to complete the full file download and is independent of the received file size.
From the debug log: the progress / fileSize both reported by android DownloadManager is
: 1310720 / 1314270

Based on the observed results, some possible causes:
a. The actual filesize is incorrectly reported by server (since there is no such problem on aTalkServer)
b. The server fails to segment the last remaining file bytes (not standard block size?) for sending. 
c. Others?

======================
![image](https://user-images.githubusercontent.com/7959606/64396772-4f40e880-d091-11e9-8539-c6ade28b805a.png)

===== aTalk debug Log ========

019-09-06 09:48:07.027 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 0 (59)
2019-09-06 09:48:08.131 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 0 (58)
2019-09-06 09:48:09.223 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 0 (57)
2019-09-06 09:48:10.316 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (60)
2019-09-06 09:48:11.417 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (59)
2019-09-06 09:48:12.519 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (58)
2019-09-06 09:48:27.994 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (44)
2019-09-06 09:48:29.104 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (43)
2019-09-06 09:48:30.207 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 2; dnProgress: 131072 (42)
2019-09-06 09:48:31.306 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 131072 (41)
2019-09-06 09:48:32.423 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (60)
2019-09-06 09:48:33.559 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (59)
2019-09-06 09:48:34.677 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (58)
2019-09-06 09:48:35.754 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (57)
....
2019-09-06 09:49:33.963 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (4)
2019-09-06 09:49:35.040 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (3)
2019-09-06 09:49:36.134 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (2)
2019-09-06 09:49:37.219 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (1)
2019-09-06 09:49:38.313 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (0)
2019-09-06 09:49:39.426 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:535)#checkProgress: Downloading file jobId: 5072; status: 4; dnProgress: 1310720 (-1)
2019-09-06 09:49:39.543 11355-11355/org.atalk.android D/(FileHttpDownloadConversation.java:261)#updateView: Cleaning up Download Manager for JobId: 5072; Size: 1314270

**Comment by licaon-kter** [comment] 2019-09-06 06:36
Ok, so you've tested with my current setup, SSLH>nginx.

But, this is working fine in Conversations, browser, curl, wget, Dino, Gajim and Converse.js.

Not sure why Android Download Manager fails. :(

**Comment by cmeng-git** [comment] 2019-09-06 09:03
Yes, you are right. There is no problem with conversations on android-P.

Someone online mentioned it is due to ClearText restriction. Try but not working either
[Download Manager returns unsuccessful download on Android 9.0](https://stackoverflow.com/questions/53323816/download-manager-returns-unsuccessful-download-on-android-9-0)

Will it be OK for me to forward the server file download link to android OS team for further investigation.

**Comment by licaon-kter** [comment] 2019-09-06 09:48
> There is no problem with conversations on android-P.

Conversations is not using the DownloadManager...

> Will it be OK for me to forward the server file download link to android OS team for further investigation.

Nope, files are cleaned periodically.

**Comment by cmeng-git** [comment] 2019-09-06 10:50
yes, I am aware that conversations is not using android DownloadManager.
Conversations adds "User-Agent", have tried on aTalk, it too does not help. Just wonder if your server denies access based on "User-Agent" settings. 

On the other hand, there is no problem to download file from aTalk test server. So it may not necessary due to android DownloadManager. aTalk may need some source update to take care of certain server specific configuration. Without android OS team assistant, I am unable to proceed further.

**Comment by licaon-kter** [comment] 2019-09-06 13:02
I'm not denying anything on purpose, maybe that's the default (?!)

Current ejabberd config: https://gist.github.com/licaon-kter/dfc0b240754ed791d270a0c310730fed

http_upload via nginx:8443 via ngx_http_upload
multiplexing via sslh:443 to nginx:8443
all my config can be seen here: https://gist.github.com/licaon-kter/54d4656cc753b98e1dc0d81a59a73faa


Looking in my logs: `$ sudo tail -n 2000 /var/log/nginx/upload.mydomain.tld_access.log|cut -d " " -f 6,9- | grep -v -e Conversations -e Gajim -e Pix -e Mozilla -e curl -e Wget|uniq`
```
"GET 200 302017 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 95710 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 95016 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1030287 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"GET 200 1080819 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 32243 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"GET 200 1314270 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1809634 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1356729 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 60961 "-" "AndroidDownloadManager/5.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"GET 200 1314270 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1080819 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 3550 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 34821 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; MHA-L29 Build/HUAWEIMHA-L29)" "-"
"PUT 201 0 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0; SM-N9005 Build/LRX21V)" "-"
"GET 200 22610 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; Nexus 5X Build/NJH47F)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "aTalk/2.0.4" "-"
"GET 206 63551 "-" "aTalk/2.0.4" "-"
"GET 200 1243199 "-" "aTalk/2.0.4" "-"
"GET 206 63551 "-" "aTalk/2.0.4" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 200 1243199 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
"GET 206 63551 "-" "AndroidDownloadManager/9 (Linux; U; Android 9; SM-N950F Build/PPR1.180610.011)" "-"
```
...I don't see any errors, neither for nginx, nor ejabberd.

**Comment by cmeng-git** [comment] 2019-09-07 02:32
Have feedback to android OS team for advice.

[Android-P DownloadManager does not return with STATUS_SUCCESSFUL even after file has been received](ssuetracker.google.com/issues/140602664)

**Comment by licaon-kter** [comment] 2019-09-10 08:47
@cmeng-git I can't use that link, first you broke it while pasting and second it requires a Google account.

**Comment by cmeng-git** [comment] 2019-09-10 09:19
It is github problem. After I have edited, github strips off the "https://"
Below is the link:
https://issuetracker.google.com/issues/140602664

**Comment by cmeng-git** [comment] 2019-11-01 08:44
Replied from android development team and closed the issue:

Thank you for reporting this issue. Unfortunately, this issue is not reproducible with our version of the AOSP source code for Pixel devices. Please file a bug with the respective OEM (Samsung in this case), as they are using their own customized version of the AOSP source code. This bug will be marked as closed.

**Closed by cmeng-git** 2019-11-01 08:44 UTC
