### ISSUE TITLE
Error when connection to xmpp server

### ISSUE THREAD

**Issue by thanhnhan290488** [cmeng-git/atalk-android#16] opened 2018-08-17 09:43 UTC
Had error show when connection xmpp server:
encounter problem during xmppconnection: the following addresses faild: '_xmpp-client._tcp.chat.quangtri.gov.vn:5222' failed because: de.measite.minidns.hla.resolutionunsuccessfulException: asking for _xmpp-client._tcp.chat.quangtri.gov.vn. In SRV yielded an error response NX_DOMAIN, 'chat.quangtri.gov.vn:5222' failed because: de.measite.minidns.miniDNSException$NullResultException: the request yielded a 'null' result while resolving
Can help me

**Comment by streaps** [comment] 2018-08-17 12:35
My guess is you used username@chat.quangtri.gov.vn:5222 for the username. I tried to connect to your server with username@chat.quangtri.gov.vn (without the port number 5222) and it worked just fine. I've got a certificate error, which means it could resolve the hostname and the XMPP connection and STARTTLS is working.

**Comment by thanhnhan290488** [comment] 2018-08-17 14:49
I tried login with DeafMSG then  successfully
But I'm using atalk and it's a bug
Although I used the same account

**Comment by cmeng-git** [comment] 2018-08-17 23:57
Please send the log file for better understanding of the problem:

How can I give feedback to the developer for any aTalk problem encountered?
http://atalk.sytes.net/faq.html#general_04

**Comment by cmeng-git** [comment] 2018-08-18 05:00
Would be able to provide me with a test account on your server for testing? You can send the account info to my gmail account.

Quick check on your sever indicates some inconsistency in your server setup i.e.
The login settings request for login using SRV, but your server does not provide a valid SRV record. This is also show up in the second error screenshot and the log message below.
```
08-18 12:02:51.102 18501-19774/org.atalk.android I/aTalk: [18270] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().970 Starting XMPP Connection...: chat.quangtri.gov.vn:5222
08-18 12:02:51.187 18501-19774/org.atalk.android I/aTalk: [18270] org.jivesoftware.smack.util.DNSUtil.resolveDomain() Could not resolve DNS SRV resource records for _xmpp-client._tcp.chat.quangtri.gov.vn. Consider adding those.
```

Also the chat.quantri.gov.vn is not a valid FQDN and therefore cannot be resolved to valid IP address for connection.

aTalk  has an online help. You may want to refer to the site for more information.
http://atalk.sytes.net/faq.html

**Comment by thanhnhan290488** [comment] 2018-08-18 06:02
You can instruct me to configure SRV accordingly

**Comment by cmeng-git** [comment] 2018-08-18 06:25
Sorry, I would not be able to help on this.  You need to refer to online help on how to configure the SRV record for your server. However this is only a problem if you want to login using SRV. You can still use aTalk without the SRV record. My earlier request is for you to refer to aTalk online help so you have a better understanding on aTalk capability.

While using your current account, I was able to connect to your server till before the authentication as I do not have the correct password. There is no problem with aTalk till this point.

However If you need me to investigate further why aTalk failed to log into your server, you need to provide me with a test account on your server. I believe the login problem lies in your xmpp server configure and setup, rather than aTalk app problem.

**Comment by streaps** [comment] 2018-08-18 10:03
> Also the chat.quantri.gov.vn is not a valid FQDN and therefore cannot be resolved to valid IP address for connection.

chat.quangtri.gov.vn works fine for me and resolves to a valid IP. Maybe you missed the g before the t.

> You can instruct me to configure SRV accordingly

see
https://wiki.xmpp.org/web/SRV_Records#XMPP_SRV_records
https://prosody.im/doc/dns

But I don't think this will solve the problem, because it should also work without a SRV record in your case.

**Comment by cmeng-git** [comment] 2018-08-18 11:05
Just perform ping chat.quangtri.gov.vn again, yes it is OK now. This morning, it returned error as "Name or service not known".

> But I don't think this will solve the problem, because it should also work without a SRV record in your case.

Yes, aTalk will fallback to normal connection if SRV record is not defined.

**Comment by cmeng-git** [comment] 2018-08-18 15:06
Have tested your server with the given test account on Note-8. There is no problem for aTalk to log onto your server. However due to huge number (>100) of contacts in the group, it really take some amount of time just to receive all the contact information from the server; it takes more than a minutes on Note-8 and 350MB bandwidth to complete the whole data transfer at aTalk start up. You may face problem with a slow android device or low network bandwidth when using aTalk.

Your server seems to have problem in handling some of the omemo data exchanges especially the prekey upload, possibly due to your server supported feature, setting configuration or server loading.

However there is a problem on Note-3 for aTalk to log to your server. It did had a problem on the SSL certificate verification. I am not sure why it complains; may be the old android OS is unable to verify your self signed certificate; on Note-8, there is no such problem..  I need further investigation on this.

**Comment by cmeng-git** [comment] 2018-08-20 01:02
There is a problem when running aTalk on Note-3 (android API-21), it was found that during ssl certificate request process, the 4-part "chat.quangtri.gov.vn" service name is being stripped to only 3-part i.e. "quangtri.gov.vn", leading to a different certificate returned by the server. Using openssl, I have verified that the returned ssl certificate is indeed belonged to "quangtri.gov.vn".  Hence the verification of the certificate failed and the process of the login is aborted by aTalk.

I have verified your test account using Conversations, it too experiences the exact same problem, seemingly the stripping of the service name is happening within the android-os. Note-8 does not have this problem.

**Comment by streaps** [comment] 2018-08-20 10:51
That explains it. I tested it with Nougat 7.1.2 (API 25), which I guess doesn't seem to have this problem anymore.

**Comment by cmeng-git** [comment] 2018-08-21 01:26
Using wireshark to capture Note-3 in SSL certificate request, I found that both A and AAAA records are being fetched during DNS resolving process. Please verify that both the records are consistent and resolved to the same IP for your server. Otherwise this may be the cause of the problem i.e. old Android always takes the AAAA record over the A as reported in the link below if it is true:
https://github.com/ubergeek42/weechat-android/issues/175#issuecomment-64445670

![atalk_srv](https://user-images.githubusercontent.com/7959606/44374840-091af480-a523-11e8-8f8d-64d04d27dc62.png)

**Comment by cmeng-git** [comment] 2018-09-07 00:13
I have installed DeafMSG on my Note-3, and found that it is actually a fork based on earlier android-jitsi open source.

It too has the same problem of fetching the incorrect ssl certificate while running on Note-3. Apparently it just accept without even validate the ssl certificate irrespective of what option that the user has selected during certification view window.

With further tracing, I found that problem is indeed lies within android when smack executed
> socket.connect(new InetSocketAddress(inetAddress, port), timeout);
where the SSL socket is created. However AS contains no source for me to trace into to fully understand the actual problem.

Based on more detail analysis of the wireshark log, I found that android only requests for the SRV, if failed then the AAAA record during IP resolving (not sure if android has cached the IP4 address). However the DNS server does not provide any AAAA record for your service name. I believe aTalk should work on Note-3 if DNS server has the AAAA i.e ip6 record defined.

**Closed** 2018-09-16 03:07 UTC
