### ISSUE TITLE
Call compatibility with Conversations

### ISSUE THREAD

**Issue by ericschdt** [cmeng-git/atalk-android#140] opened 2020-04-22 18:52 UTC
aTalk seems to use ZRTP, but Conversations uses DTLS for a audio / video call. Would you mind to implement the latter to make both (a little bit more) compatible?

That would make aTalk more interesting again. Looking forward to to having a nice aTalk <-> Conversations call.

**Comment by dingdongnigetou** [comment] 2020-04-24 02:51
> aTalk seems to use ZRTP, but Conversations uses DTLS for a audio / video call. Would you mind to implement the latter to make both (a little bit more) compatible?

Do you mean this [Conversations ](https://github.com/siacs/Conversations) ? It does not support audio/video call actually.

**Comment by susobaco** [comment] 2020-04-24 08:12
They are implemented.
https://github.com/siacs/Conversations/tree/jingle

**Comment by cmeng-git** [comment] 2020-04-24 11:29
Hi MilanKral,

Would you able to help. I have disabled DTLS feature on aTalk as the source is not working. Appreciate if you can take a look and fix the problem if possible.

**Comment by dingdongnigetou** [comment] 2020-04-26 03:16
> They are implemented.
> https://github.com/siacs/Conversations/tree/jingle

Awesome, let me try it.

**Comment by cmeng-git** [comment] 2020-05-01 23:47
> What's left to make DTLS working? In 2.2.4 the option is grayed out and not selectable.

In my last test on DTLS, even when enabled, the call status is still indicated that it is a non-secure call. Therefore I have disabled the option until have time to study the cause in details.

**Comment by cmeng-git** [comment] 2020-05-13 02:30
aTalk v2.2.5 implemented DTLS_SRTP call encryption DTLSv12/DTLSv10 protocols and additional CipherSuites support. Please verify.

**Comment by ericschdt** [comment] 2020-05-18 12:52
Tested it again with 2.2.5 and DTLS enabled.

Conversations 2.8.3 --> aTalk 2.2.5
Rings -- Nothing

Conversations 2.8.3 --> aTalk 2.2.5
While ringing, callback from aTalk results in "busy" state at aTalk's end.
Conversations has a tie break built in by now: https://github.com/iNPUTmice/Conversations/commit/4d3d3a703871be4fe78a9bcdfdf954c9d7aa375b

aTalk 2.2.5 --> Conversations 2.8.3
![atalk](https://user-images.githubusercontent.com/43318127/82215020-3cf89900-9906-11ea-895c-f126a7133606.jpg)

**Comment by cmeng-git** [comment] 2020-05-18 13:13
Conversations call setup protocol is not compatible with aTalk.

**Comment by ericschdt** [comment] 2020-06-09 11:20
@cmeng-git Please see https://nl.movim.eu/?node/pubsub.movim.eu/berlin-xmpp-meetup/3e091c00-5e20-4727-a61d-c92a247b106

> During the next (virtual) meetup, Daniel and Holger will give an introduction to the technologies used for implementing audio/video calls with XMPP by example of the Android client Conversations, which recently gained A/V support. Topics discussed will include XMPP's Jingle extensions, ICE/STUN/TURN, (S)RTP, and WebRTC. As time permits, we'll also hear an interesting bonus talk by eta on integrating the A/V solution with Asterisk.
> When? Wednesday, 2020-06-10 18:00 CEST (always 2ⁿᵈ Wednesday of every month)

**Comment by cmeng-git** [comment] 2020-06-09 13:04
Thanks for the info.

Actually aTalk has already 90% through implementation to work with Conversations. There remain two more problems to be resolved when making video call originated from Conversations. Hopefully to get them resolved in the next two weeks.

**Comment by iNPUTmice** [comment] 2020-06-10 11:19
@cmeng-git it might be of interest to you that the latest version of Conversations (2.8.6) supports direct jingle initiation (while previously versions required Jingle Message Initiation) - so getting it compatible with atalk should be simpler now.
In general Conversations tries to put human readable text in the termination reason in case something goes wrong. However if that isn’t enough; or if you discover any bugs in the Conversations side of things feel free to ping me.

**Comment by cmeng-git** [comment] 2020-06-10 23:33
Many thanks for the update.
aTalk has implemented XEP-0353 Jingle Message Initiation and is working well with Conversations.
XEP-0353 has resolved major issue when making call with buddy with multiple resources logged.

The major problem aTalk is facing is how the jingle messages are being received. Current design put a major restriction on the way the received jingle messages are processed.
1. aTalk/Jitsi implementations:
    a. transport-info's are embedded within session-initiate stanza;
    b. transport-info's are sent prior to session-accept stanza; - can be processed individually without problem
2. Conversations implementations:
    a. transport-info's are sent per media after session-initiate stanza;
    b. transport-info's are sent per media after session-accept stanza;
* All the transport-info's must be combined and processed in one go; otherwise ice4j will prune any unspecified media from the ice agent.

Currently aTalk has resolved all the issues except when a video call is initiated from Conversations.
From debug log, all the transport-info/candidates were received, validated, and paired correctly for both the audio and video medias.

However for some unknown reason, the received video media is piped to audio decoder for process; and depicted video decoder of a video media stream to process. It seems the problem is related to Ice Agent in ice4j library,  still under investigation for the a solution.

So far the test results on Conversations are good without much problem. Will certainly inform you if aTalk need help from Conversations.

**Comment by cmeng-git** [comment] 2020-06-15 10:45
Just release v2.3.0.
Audio call should be OK. There are still having problems with video call. Need to contact Conversations - seems like the problems are from Conversations.

**Comment by cmeng-git** [comment] 2020-07-14 00:59
aTalk v2.3.1 has just released, believe this is now working with Conversations.
For any further issues for call with Conversations, please feedback to Conversations for further actions.

**Closed by cmeng-git** 2020-07-14 00:59 UTC
