### ISSUE TITLE
Don't show audio/video icons for MUCs

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#67] opened 2019-11-05 09:52 UTC
2.1.1 F-Droid

For ejabberd and Conversations MUCs, in the roster view, the icons appear and disappear at random.

But, since it didn't actually finish loading the actual MUC even if it's opened for the last 15min (how do I know that? Well, all the users are named "mucid@conference.domain.tld") I guess aTalk still believes this could be an user instead.

**Comment by cmeng-git** [comment] 2019-11-05 23:54
Actually the "mucid@conference.domain.tld" should not be listed in the roster (contact list) view. This is the aTalk problem I need to fix.

However so far I am unable to find a consistent way to get aTalk to list the mcu user in roster view.
Appreciate if you can describe the way you manage to get aTalk to show mcu to list in roster view, so I can find the cause.

**Comment by licaon-kter** [comment] 2019-11-06 01:07
They are listed as "not in contact list" or whatever is that section called.

The interesting thing is that on start it gets all the messages, many many messages, I get the notifications, many of them, with proper usernames, but if I try to open the MUC I see all the users as mucid@...

Oh, and the dot (the one that's green for online and grey if not) is always gray, even though I have all the messages, and get new ones as they come.

**Comment by cmeng-git** [comment] 2019-11-06 01:47
> They are listed as "not in contact list" or whatever is that section called.

Any buddy/contact that are not in your roster shared group or in your subscription list will appear in NotInContactList section as what aTalk refer to as Volatile Contact. In original aTalk forked source, this volatile contact are completely being ignored; and user is unable to receive any message sent from these volatile contacts include the message broadcast by the server. aTalk added the feature to allow receive messages from these volatile contacts (like conversations). But look like implementation is not clean at this point, and needs further improvement.

> The interesting thing is that on start it gets all the messages, many many messages, I get the notifications, many of them, with proper usernames, but if I try to open the MUC I see all the users as mucid@...

When you start aTalk and login the server, server will automatically send you all the messages that are being sent while you are offline or refer to as offline messages. When you join a muc, server will also send you the conference history messages (if option is enabled on server).

> Oh, and the dot (the one that's green for online and grey if not) is always gray, even though I have all the messages, and get new ones as they come.

What you see the messages are likely to be the history messages; the history messages are sent by server even when the muc user is offline (grey dot). The green dot (presence) status of the muc user is sent and notified by server. aTalk just display the status as it is being received from server. 

> but if I try to open the MUC I see all the users as mucid@...

If I understand it correctly, you are saying that all the muc users are being named the same i.e. "mucid@conference.domain.tld" even the messages are from different muc users.
Sorry, this is the first time I am told of this problem. Please send me the debug log so I can better understand the problem.

**Comment by cmeng-git** [comment] 2019-11-07 00:28
Problem fixed in v2.1.2 release
Conference users will not be listed in NotInContactList section.

**Closed** 2019-11-14 06:12 UTC
