### ISSUE TITLE
Error while sending images

### ISSUE THREAD

**Issue by ejabberedatalk** [cmeng-git/atalk-android#169] opened 2020-12-09 04:00 UTC
I have installed your **atalk app directly from google playstore** to 2 different android phones and logged in with different users, while sending images from app to another app, I am getting attached error messages. This message is on destination app. Backend is my own ejabberd server, I have opened all ports, configured all properly.

I have installed other xmpp client on both phones and logged with same user and send images, they are delivered without any error so there is not issue from server side, please fix this error. 
![atalk image send error](https://user-images.githubusercontent.com/57741936/101583594-6b70bb00-39a1-11eb-9238-453ec7d3f4ae.jpeg)

**Comment by cmeng-git** [comment] 2020-12-09 05:16
Please provide the following info:
a. What are the android OS for the two devices.
b. Which aTalk version have you installed
c. Repeat the same test, then send me the debug log for both the devices.

**Comment by ejabberedatalk** [comment] 2020-12-09 07:00
one phone using android version 9, another phone using android 8
I have installed atalk latest version from android playstore (2.4.4)
[lenov_atalk_log.txt](https://github.com/cmeng-git/atalk-android/files/5664022/lenov_atalk_log.txt)
[samsung_atalk_log.txt](https://github.com/cmeng-git/atalk-android/files/5664024/samsung_atalk_log.txt)

**Comment by cmeng-git** [comment] 2020-12-09 23:23
Please use the "Report Bugs" option in the About to send me the debug log"

![image](https://user-images.githubusercontent.com/7959606/101700735-8a15a580-3ab8-11eb-9f9b-f45f96f5c776.png)

**Comment by cmeng-git** [comment] 2020-12-14 04:41
Please send me the aTalk debug log if you are still facing the problem, and still need my help to investigate.
I am unable to proceed the investigation further, as I am unable to reproduce the problem on my side.

Please note that you must provide storage write access etc to aTalk to ensure aTalk works as expected.

**Comment by ejabberedatalk** [comment] 2020-12-14 08:04
Sorry I am not able to send debulog using "Report Bugs" option in app, I am not compiling and installing from android studio, I installed app from playstore in both devices. I have given all permissions to both apps in both devices. 

I have used my own ejabbered server, open all ports to public. I am able to send messages, make video, audio calls, but sending image failed with same error "No response received within reply timeout." But If I try multiple times sending images, some time, it is sending image successfully, but most of the time giving error. 

And I have tried using anther server, created 2 accounts in public xmpp server (xmpp.jp)
1) atalk1@xmpp.jp/admin@123
2) atalk2@xmpp.jp/admin@123

Logged with above users into 2 apps and send images, I got same error for first 3 times, but 4th time image is sent successfully 

For both devices, I have used below settings:
1) Send/Receive thumbnail preview is enabled
2) Auto accept max file size. set to 50 MB
3) Using "unencrypted" in chat 

If possible, please install app from playstore and login with above users I have given and send images to replicate this error

**Comment by cmeng-git** [comment] 2020-12-15 00:04
I just re-installed one of my test android devices Galaxy J7 with apk from playstore. I see there is no problem with the apk released on playstore, the file transfer works as expected. Both the xmpp accounts are registered on my own ejabberd xmpp test server. The xmpp server supports relay proxy for file transfer. 

What I observed is that the file transfer falls back to using server proxy service when one of the device is using mobile network i.e. behind firewall. Based on your last comment, without the debug info, below is my best guess what are the possible problems in your case.

a. I believe that your xmpp server is installed on an external machine, and either one of the two or both the android devices are behind firewall.

b. Currently aTalk file transfer in plain mode supports only SOCK5, IBB or via proxy. aTalk currently does not implement jingle file transfer see https://github.com/cmeng-git/atalk-android/issues/64

c. Assuming (a) is correct, then the only file transfer mode in your test environment is IBB mode. The IBB Mode uses in band bandwidth and the file is broken into blocks before sending. The transfer speed is slow, and is not the ideal candidate for big file size transfer. When the network condition is no ideal, the file transfer may fail.

d. I believe you do not experience the same problem for file transfer in omemo session.

Can you enable proxy service on your xmpp server if no done so, and see if this help?

Actually the "Report Bugs" option is available in both aTalk debug and release versions. The option can be found in the "About" main menu. If my above observation is not correct, I still need your debug log for further investigation.

**Comment by ejabberedatalk** [comment] 2020-12-15 20:17
I have enabled proxy in ejabbered, then removed and installed apps again then send messengers, I got different error realeted to SOCK5 for first time in both apps, but from second image onwards, all were sent successfully.

I repeated this step by installing both apps again, I got same error with first image, and then all other images sent successfully.

I think it is issue with network or server, not client. We can close this issue. Thanks you

**Comment by cmeng-git** [comment] 2020-12-16 03:20
Thank for sharing your finding. Will close the issue.

**Closed by cmeng-git** 2020-12-16 03:20 UTC

**Comment by cmeng-git** [comment] 2021-01-05 01:48
Actually there was a problem in v2.4.4 and v2.4.5 in file sharing as observed by you. The problem has been fixed in aTalk 2.4.6 i.e.:

Fix file sharing failed when sending thumbnail on request; smack v4.4.0 throws NPE without max-age attribute in BoBData stanza
